package presenters;

public enum Events {
    ADD_PROCESS, ACCEPT, CANCEL, EDIT_PROCESS, DELETE_PROCESS, VIEW_INFO, COMMUNICATE_PROCESS, ACCEPT_EDIT,
    CANCEL_EDIT, EXIT, INIT_SIMULATION, CLOSE_INFO, NEW_SIMULATION, EXPORT, COMMUNICATE, CANCEL_COMMUNICATE,
    DELETE_COMMUNICATE
}
